# Cell states

UNOCCUPIED = ''

# Civ

TECH_DEVELOPMENT = 'Develop'
TERRITORIAL_EXPANSION = 'Expand'
POPULATION_GROWTH = 'Growth'
TERRITORIAL_STABILIZATION = 'Stabilize'

CIV_PRIORITIES = [
    TECH_DEVELOPMENT,
    TERRITORIAL_EXPANSION,
    POPULATION_GROWTH,
    TERRITORIAL_STABILIZATION
]
